mumble_config_users: 10
mumble_config_port: 64738
mumble_config_host: mumble.botcodes.dev

wireguard_tz: Asia/Karachi
wireguard_server_port: 51820
wireguard_server_private_key: QDZWrnN+C09A6zcrQuleMZBtDnHI4V6rCgs0YHHTWEI=
wireguard_peer_public_key: xAHlnrixknp12iDDSy5Oo34/0Y/uBB/JxmuVluJAWVY=
wireguard_peer_preshared_key: LAk7MCh3gVEDBVeKt83RIkHeVvBP1pNtUJowfssanSM=
