- hosts: home-server
  become: false

  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.config/containers/systemd/home-server/{{ item.path }}"
        state: directory
        mode: '{{ item.mode }}'
      with_community.general.filetree: quadlets/home-server
      when: item.state == 'directory'

    - name: Deploy Quadlets
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: "{{ ansible_facts.env.HOME }}/.config/containers/systemd/home-server/{{ item.path | regex_replace('\\.j2$', '') }}"
      with_community.general.filetree: quadlets/home-server/
      when:
        - item.state == 'file'
        - not item.path.endswith('~')
      register: quadlet_results

    - name: Reload user systemd
      systemd:
        daemon_reload: true
        scope: user

    - name: Restart changed container services
      systemd:
        name: >-
          {{
          item.item
          | basename
          | regex_replace('\.container(\.j2)?$', '')
          }}.service
        state: restarted
        scope: user
      loop: "{{ quadlet_results.results }}"
      when:
        - item.changed
        - item.item is match('.*\\.container(\\.j2)?$')

    - name: Setup Wireguard 
      become: true
      block:
        - name: Install WireGuard
          ansible.builtin.package:
            name:
              - wireguard
              - wireguard-tools
              - iptables
            state: present

        - name: Enable IP forwarding
          ansible.posix.sysctl:
            name: net.ipv4.ip_forward
            value: "1"
            state: present
            reload: true

        - name: Ensure directories exists
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - /etc/wireguard/

        - name: Deploy configs
          ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest}}"
            owner: root
            group: root
            mode: "0600"
          notify:
            - Restart WireGuard
          loop:
            - src: configs/home-server/wireguard/wg0.conf.j2
              dest: /etc/wireguard/wg0.conf

        - name: Ensure services are running
          ansible.builtin.systemd_service:
            name: "{{ item }}"
            state: started
            enabled: true
          loop:
            - wg-quick@wg0

  handlers:
    - name: Restart WireGuard
      become: true
      ansible.builtin.systemd_service:
        name: wg-quick@wg0
        state: restarted

- hosts: vps
  become: false

  tasks:
    - name: Create base quadlet dir
      ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.config/containers/systemd/vps"
        state: directory

    - name: Deploy Quadlets
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: "{{ ansible_facts.env.HOME }}/.config/containers/systemd/vps/{{ item.path | regex_replace('\\.j2$', '') }}"
      with_community.general.filetree: quadlets/vps/
      when:
        - item.state == 'file'
        - not item.path.endswith('~')

    - name: Reload user systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user

    - name: Setup Wireguard 
      become: true
      block:
        - name: Install WireGuard and nftables
          ansible.builtin.package:
            name:
              - wireguard
              - wireguard-tools
              - iptables
              - nftables
            state: present

        - name: Enable IP forwarding
          ansible.posix.sysctl:
            name: net.ipv4.ip_forward
            value: "1"
            state: present
            reload: true

        - name: Ensure directories exists
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
          loop:
            - /etc/wireguard/
            - /etc/

        - name: Deploy configs
          ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest}}"
            owner: root
            group: root
            mode: "0600"
          notify:
            - Restart WireGuard
            - Restart nftables
          loop:
            - src: configs/vps/wireguard/wg0.conf.j2
              dest: /etc/wireguard/wg0.conf
            - src: configs/vps/nftables/nftables.conf.j2
              dest: /etc/nftables.conf

        - name: Ensure services are running
          ansible.builtin.systemd_service:
            name: "{{ item }}"
            state: started
            enabled: true
          loop:
            - wg-quick@wg0
            - nftables

  handlers:
    - name: Restart WireGuard
      become: true
      ansible.builtin.systemd_service:
        name: wg-quick@wg0
        state: restarted

    - name: Restart nftables
      become: true
      ansible.builtin.systemd_service:
        name: nftables
        state: restarted
